import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.orders': 'Orders',
    'nav.communication': 'Communication',
    'nav.finance': 'Finance',
    'nav.leads': 'Leads',
    'nav.profile': 'Profile',
    'nav.analytics': 'Analytics',
    
    // Products
    'products.title': 'Products List',
    'products.subtitle': 'Manage your product catalog and inventory',
    'products.addProduct': 'Add Product',
    'products.totalProducts': 'Total Products',
    'products.activeProducts': 'Active Products',
    'products.lowStock': 'Low Stock',
    'products.outOfStock': 'Out of Stock',
    'products.search': 'Search products, SKUs, or categories...',
    'products.filters': 'Filters',
    'products.category': 'Category',
    'products.status': 'Status',
    'products.stockLevel': 'Stock Level',
    'products.priceRange': 'Price Range',
    'products.allCategories': 'All Categories',
    'products.allStatuses': 'All Statuses',
    'products.allLevels': 'All Levels',
    'products.allPrices': 'All Prices',
    'products.clearFilters': 'Clear all filters',
    'products.selected': 'selected',
    'products.updateStatus': 'Update Status',
    'products.updateStock': 'Update Stock',
    'products.delete': 'Delete',
    'products.product': 'Product',
    'products.price': 'Price',
    'products.stock': 'Stock',
    'products.sales': 'Sales',
    'products.actions': 'Actions',
    'products.units': 'units',
    'products.sold': 'sold',
    'products.loadMore': 'Load more',
    'products.remaining': 'products remaining',
    'products.noProducts': 'No products found',
    'products.noProductsDesc': 'No products match your search and filter criteria.',
    
    // Inventory Management
    'inventory.title': 'Inventory Management',
    'inventory.subtitle': 'Track and manage your product inventory levels',
    'inventory.totalProducts': 'Total Products',
    'inventory.inStock': 'In Stock',
    'inventory.lowStock': 'Low Stock',
    'inventory.outOfStock': 'Out of Stock',
    'inventory.totalValue': 'Total Value',
    'inventory.exportInventory': 'Export Inventory',
    'inventory.importStockUpdates': 'Import Stock Updates',
    'inventory.bulkUpdateStock': 'Bulk Update Stock',
    'inventory.bulkUpdatePrice': 'Bulk Update Price',
    'inventory.export': 'Export',
    'inventory.delete': 'Delete',
    'inventory.selected': 'items selected',
    'inventory.searchPlaceholder': 'Search products by name, SKU, or category...',
    'inventory.allStatus': 'All Status',
    'inventory.active': 'Active',
    'inventory.inactive': 'Inactive',
    'inventory.draft': 'Draft',
    'inventory.allStockLevels': 'All Stock Levels',
    'inventory.inStockFilter': 'In Stock (10+)',
    'inventory.lowStockFilter': 'Low Stock (1-9)',
    'inventory.outOfStockFilter': 'Out of Stock',
    'inventory.product': 'Product',
    'inventory.category': 'Category',
    'inventory.price': 'Price',
    'inventory.stock': 'Stock',
    'inventory.inventoryValue': 'Inventory Value',
    'inventory.status': 'Status',
    'inventory.actions': 'Actions',
    'inventory.quickEditStock': 'Quick Edit Stock',
    'inventory.duplicate': 'Duplicate Product',
    'inventory.editProduct': 'Edit Product',
    'inventory.deleteProduct': 'Delete Product',
    'inventory.markAsDraft': 'Mark as Draft',
    'inventory.markAsActive': 'Mark as Active',
    'inventory.updateStockTitle': 'Update Stock',
    'inventory.updatePriceTitle': 'Update Price',
    'inventory.stockQuantity': 'Stock Quantity',
    'inventory.updateMode': 'Update Mode',
    'inventory.setValue': 'Set to value',
    'inventory.addToCurrent': 'Add to current',
    'inventory.subtractFromCurrent': 'Subtract from current',
    'inventory.percentageChange': 'Percentage change',
    'inventory.updateProducts': 'Update Products',
    'inventory.confirmDelete': 'Are you sure you want to delete',
    'inventory.confirmDeleteMultiple': 'products?',
    'inventory.stockStatus': {
      'outOfStock': 'Out of Stock',
      'lowStock': 'Low Stock', 
      'inStock': 'In Stock'
    },

    // Bulk Upload
    'bulkUpload.title': 'Bulk Product Import',
    'bulkUpload.subtitle': 'Import multiple products using CSV file',
    'bulkUpload.uploadCsv': 'Upload Your Product CSV',
    'bulkUpload.uploadDescription': 'Upload a CSV file containing your product data. Need help getting started?',
    'bulkUpload.beforeStart': 'Before you start:',
    'bulkUpload.downloadTemplate': 'Download our template to ensure proper formatting',
    'bulkUpload.requiredFields': 'Include required fields: Product Name, SKU, Price, Category',
    'bulkUpload.utf8Encoding': 'Use UTF-8 encoding for special characters',
    'bulkUpload.maxFileSize': 'Maximum file size: 10MB',
    'bulkUpload.downloadCsvTemplate': 'Download CSV Template',
    'bulkUpload.uploadCsvFile': 'Upload CSV File',
    'bulkUpload.dropFile': 'Drop your CSV file here',
    'bulkUpload.dragAndDrop': 'Drag and drop your CSV file here, or click to select',
    'bulkUpload.mapColumns': 'Map CSV Columns',
    'bulkUpload.mapDescription': 'Map your CSV columns to the corresponding product fields',
    'bulkUpload.selectColumn': 'Select CSV column...',
    'bulkUpload.required': '*',
    'bulkUpload.validateData': 'Validate Data',
    'bulkUpload.back': 'Back',
    'bulkUpload.validationResults': 'Data Validation Results',
    'bulkUpload.reviewErrors': 'Review validation results and fix any errors before proceeding',
    'bulkUpload.totalRows': 'Total Rows',
    'bulkUpload.valid': 'Valid',
    'bulkUpload.errors': 'Errors',
    'bulkUpload.warnings': 'Warnings',
    'bulkUpload.validationIssues': 'Validation Issues',
    'bulkUpload.row': 'Row',
    'bulkUpload.field': 'Field',
    'bulkUpload.value': 'Value',
    'bulkUpload.issue': 'Issue',
    'bulkUpload.type': 'Type',
    'bulkUpload.error': 'error',
    'bulkUpload.warning': 'warning',
    'bulkUpload.backToMapping': 'Back to Mapping',
    'bulkUpload.previewImport': 'Preview Import',
    'bulkUpload.productsWillBeImported': 'products will be imported',
    'bulkUpload.reviewProducts': 'Review {count} products that will be imported',
    'bulkUpload.showingFirst': 'Showing first 20 of',
    'bulkUpload.products': 'products',
    'bulkUpload.backToValidation': 'Back to Validation',
    'bulkUpload.import': 'Import',
    'bulkUpload.importProducts': 'Import {count} Products',
    'bulkUpload.importing': 'Importing...',
    'bulkUpload.importComplete': 'Import Complete!',
    'bulkUpload.processing': 'Processing {processed} of {total} products',
    'bulkUpload.successfullyImported': 'Successfully imported {success} products',
    'bulkUpload.importProgress': 'Import Progress',
    'bulkUpload.successful': 'Successful',
    'bulkUpload.failed': 'Failed',
    'bulkUpload.totalProcessed': 'Total Processed',
    'bulkUpload.viewProducts': 'View Products',
    'bulkUpload.importMoreProducts': 'Import More Products',

    // Analytics
    'analytics.growth.title': 'Growth Analytics',
    'analytics.growth.subtitle': 'Track your business growth and performance trends',
    'analytics.growth.revenueGrowth': 'Revenue Growth',
    'analytics.growth.ordersGrowth': 'Orders Growth', 
    'analytics.growth.customerGrowth': 'Customer Growth',
    'analytics.growth.aovGrowth': 'AOV Growth',
    'analytics.growth.revenueGrowthTrend': 'Revenue Growth Trend',
    'analytics.growth.ordersGrowthTrend': 'Orders Growth Trend',
    'analytics.growth.customerAcquisition': 'Customer Acquisition',
    'analytics.growth.geographicGrowth': 'Geographic Growth',
    'analytics.growth.currentPeriod': 'Current Period',
    'analytics.growth.previousPeriod': 'Previous Period',
    'analytics.growth.newCustomers': 'New Customers',
    'analytics.growth.returningCustomers': 'Returning Customers',
    'analytics.growth.revenue': 'revenue',
    'analytics.growth.insights': 'Growth Insights & Recommendations',
    'analytics.growth.strongPerformance': 'Strong Performance',
    'analytics.growth.strongPerformanceDesc': 'Revenue growth of {growth} is excellent. Continue current marketing strategies.',
    'analytics.growth.customerAcquisitionDesc': 'Focus on customer retention strategies to maintain the {growth} growth rate.',
    'analytics.growth.aovOptimization': 'AOV Optimization',
    'analytics.growth.aovOptimizationDesc': 'Consider upselling strategies to further improve the average order value growth.',
    'analytics.growth.periodComparison': 'Period Comparison',
    'analytics.growth.metric': 'Metric',
    'analytics.growth.totalRevenue': 'Total Revenue',
    'analytics.growth.totalOrders': 'Total Orders',
    'analytics.growth.newCustomersTable': 'New Customers',
    'analytics.conversion.title': 'Conversion Analytics',
    'analytics.conversion.subtitle': 'Analyze your sales funnel and conversion rates',
    'analytics.timeRange.7d': 'Last 7 days',
    'analytics.timeRange.30d': 'Last 30 days', 
    'analytics.timeRange.90d': 'Last 90 days',
    'analytics.timeRange.1y': 'Last year',

    // Category Tree
    'addProduct.selectCategory': 'Select Category',
    'addProduct.searchCategories': 'Search categories...',
    'addProduct.noCategoriesFound': 'No categories found',
    'addProduct.selectedCategory': 'Selected Category',
    'addProduct.categoryPath': 'Category Path',
    'addProduct.leafCategoriesOnly': 'Please select a specific category (not a parent category)',
    'addProduct.notSelected': 'Not selected',
    
    // Product Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.draft': 'Draft',
    'status.outOfStock': 'Out of Stock',
    
    // Stock Levels
    'stock.inStock': 'In Stock',
    'stock.lowStock': 'Low Stock',
    'stock.outOfStock': 'Out of Stock',
    
    // Price Ranges
    'price.under1000': 'Under 1,000 SAR',
    'price.1000to5000': '1,000 - 5,000 SAR',
    'price.5000to20000': '5,000 - 20,000 SAR',
    'price.over20000': 'Over 20,000 SAR',
    
    // Add/Edit Product
    'addProduct.title': 'Add New Product',
    'editProduct.title': 'Edit Product',
    'addProduct.step': 'Step',
    'addProduct.of': 'of',
    'addProduct.saving': 'Saving...',
    'addProduct.saved': 'Saved',
    'addProduct.saveError': 'Save Error',
    'addProduct.basicInfo': 'Basic Information',
    'addProduct.detailsMedia': 'Details & Media',
    'addProduct.pricingInventory': 'Pricing & Inventory',
    'addProduct.reviewPublish': 'Review & Publish',
    'addProduct.nameEn': 'Product Name (English)',
    'addProduct.nameAr': 'Product Name (Arabic)',
    'addProduct.sku': 'Product Code (SKU)',
    'addProduct.category': 'Category',
    'addProduct.tags': 'Tags',
    'addProduct.addTag': 'Add Tag',
    'addProduct.descriptionEn': 'Description (English)',
    'addProduct.descriptionAr': 'Description (Arabic)',
    'addProduct.images': 'Product Images (max 10 images)',
    'addProduct.dragImages': 'Drag images here or click to select',
    'addProduct.imageFormat': 'PNG, JPG, GIF up to 10MB each',
    'addProduct.specifications': 'Technical Specifications',
    'addProduct.addSpec': 'Add Specification',
    'addProduct.sellingPrice': 'Selling Price (SAR)',
    'addProduct.costPrice': 'Cost Price (SAR)',
    'addProduct.stockQuantity': 'Stock Quantity',
    'addProduct.lowStockThreshold': 'Low Stock Alert Threshold',
    'addProduct.dimensions': 'Dimensions & Weight',
    'addProduct.length': 'Length (cm)',
    'addProduct.width': 'Width (cm)',
    'addProduct.height': 'Height (cm)',
    'addProduct.weight': 'Weight (kg)',
    'addProduct.productStatus': 'Product Status',
    'addProduct.review': 'Product Review',
    'addProduct.productInfo': 'Product Information',
    'addProduct.statusSettings': 'Status & Settings',
    'addProduct.name': 'Name',
    'addProduct.productCode': 'Product Code',
    'addProduct.stockCount': 'Stock',
    'addProduct.imageCount': 'Images',
    'addProduct.specCount': 'Specifications',
    'addProduct.tagCount': 'Tags',
    'addProduct.description': 'Description',
    'addProduct.previous': 'Previous',
    'addProduct.next': 'Next',
    'addProduct.saveChanges': 'Save Changes',
    'addProduct.publishProduct': 'Publish Product',
    'addProduct.unsavedChanges': 'You have unsaved changes',
    'addProduct.saveNow': 'Save Now',
    'addProduct.profitMargin': 'Profit margin',
    'addProduct.lowStockAlert': 'You will be notified when stock reaches this number',
    'addProduct.autoSku': 'Will be generated automatically based on product name',
    
    // Validation Messages
    'validation.required': 'This field is required',
    'validation.nameRequired': 'Product name is required',
    'validation.nameArRequired': 'Arabic name is required',
    'validation.skuRequired': 'Product code is required',
    'validation.categoryRequired': 'Category is required',
    'validation.descriptionRequired': 'Description is required',
    'validation.descriptionArRequired': 'Arabic description is required',
    'validation.priceRequired': 'Price must be greater than zero',
    'validation.stockNegative': 'Stock cannot be negative',
    'validation.fixErrors': 'Please fix the following errors:',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.settings': 'Settings',
    
    // Orders
    'orders.title': 'Orders Management',
    'orders.subtitle': 'Manage and track your customer orders',
    'orders.totalOrders': 'Total Orders',
    'orders.pendingOrders': 'Pending Orders',
    'orders.completedOrders': 'Completed Orders',
    'orders.cancelledOrders': 'Cancelled Orders',
    'orders.search': 'Search orders, customers, or products...',
    'orders.orderNumber': 'Order Number',
    'orders.customer': 'Customer',
    'orders.date': 'Order Date',
    'orders.total': 'Total Amount',
    'orders.status': 'Status',
    'orders.actions': 'Actions',
    'orders.viewDetails': 'View Details',
    'orders.contactCustomer': 'Contact Customer',
    'orders.updateStatus': 'Update Status',
    'orders.generateInvoice': 'Generate Invoice',
    'orders.noOrders': 'No Orders Found',
    'orders.noOrdersDesc': 'No orders match your search and filter criteria.',
    'orders.filterBy': 'Filter by',
    'orders.allStatuses': 'All Statuses',
    'orders.dateRange': 'Date Range',
    'orders.customerType': 'Customer Type',
    'orders.orderValue': 'Order Value',
    'orders.bulkActions': 'Bulk Actions',
    'orders.selectedOrders': 'selected orders',
    'orders.markAsProcessing': 'Mark as Processing',
    'orders.markAsShipped': 'Mark as Shipped',
    'orders.markAsDelivered': 'Mark as Delivered',
    'orders.exportSelected': 'Export Selected',
    'orders.orderDetails': 'Order Details',
    'orders.orderTimeline': 'Order Timeline',
    'orders.paymentInfo': 'Payment Information',
    'orders.shippingInfo': 'Shipping Information',
    'orders.customerInfo': 'Customer Information',
    'orders.orderItems': 'Order Items',
    'orders.orderSummary': 'Order Summary',
    'orders.subtotal': 'Subtotal',
    'orders.tax': 'VAT (15%)',
    'orders.shipping': 'Shipping',
    'orders.discount': 'Discount',
    'orders.grandTotal': 'Grand Total',
    
    // Order Statuses
    'orderStatus.pending': 'Pending',
    'orderStatus.confirmed': 'Confirmed',
    'orderStatus.processing': 'Processing',
    'orderStatus.shipped': 'Shipped',
    'orderStatus.delivered': 'Delivered',
    'orderStatus.cancelled': 'Cancelled',
    'orderStatus.refunded': 'Refunded',
    
    // Communication
    'communication.title': 'Communication Hub',
    'communication.subtitle': 'Manage customer communications and inquiries',
    'communication.activeChats': 'Active Chats',
    'communication.unreadMessages': 'Unread Messages',
    'communication.searchCustomers': 'Search customers...',
    'communication.allPriorities': 'All Priorities',
    'communication.highPriority': 'High Priority',
    'communication.mediumPriority': 'Medium Priority',
    'communication.lowPriority': 'Low Priority',
    'communication.online': 'Online now',
    'communication.lastSeen': 'Last seen',
    'communication.typeMessage': 'Type your message...',
    'communication.selectChat': 'Select a conversation to start',
    'communication.selectChatDesc': 'Choose a customer from the list to view your conversation',
    'communication.newConversation': 'New Conversation',
    'communication.templates': 'Templates',
    'communication.quickReplies': 'Quick Replies',
    'communication.attachments': 'Attachments',
    'communication.emoji': 'Emoji',
    'communication.send': 'Send',
    'communication.minutes': 'm',
    'communication.hours': 'h',
    'communication.days': 'd',
    'communication.priority': 'Priority',
    'communication.tags': 'Tags',
    'communication.customerInfo': 'Customer Information',
    'communication.conversationHistory': 'Conversation History',
    'communication.orderHistory': 'Order History',
    'communication.notes': 'Notes',
    'communication.addNote': 'Add Note',
    'communication.markAsRead': 'Mark as Read',
    'communication.markAsImportant': 'Mark as Important',
    'communication.archive': 'Archive',
    'communication.block': 'Block Customer',
    'communication.call': 'Call',
    'communication.videoCall': 'Video Call',
    'communication.email': 'Email',
    
    // Finance
    'finance.title': 'Finance Dashboard',
    'finance.subtitle': 'Track revenue, payments, and financial reports',
    'finance.totalRevenue': 'Total Revenue',
    'finance.pendingPayments': 'Pending Payments',
    'finance.overduePayments': 'Overdue Payments',
    'finance.averagePaymentTime': 'Average Payment Time',
    'finance.transactions': 'transactions',
    'finance.days': 'days',
    'finance.fromLastMonth': 'from last month',
    'finance.exportReport': 'Export Report',
    'finance.revenueOverTime': 'Revenue Over Time',
    'finance.paymentMethods': 'Payment Methods',
    'finance.recentTransactions': 'Recent Transactions',
    'finance.invoiceNumber': 'Invoice Number',
    'finance.customer': 'Customer',
    'finance.amount': 'Amount',
    'finance.status': 'Status',
    'finance.paymentMethod': 'Payment Method',
    'finance.dueDate': 'Due Date',
    'finance.actions': 'Actions',
    'finance.allStatuses': 'All Statuses',
    'finance.revenue': 'Revenue',
    'finance.payments': 'Payments',
    'finance.period': 'Period',
    'finance.week': 'Week',
    'finance.month': 'Month',
    'finance.quarter': 'Quarter',
    'finance.year': 'Year',
    
    // Payment Statuses
    'paymentStatus.paid': 'Paid',
    'paymentStatus.pending': 'Pending',
    'paymentStatus.overdue': 'Overdue',
    'paymentStatus.failed': 'Failed',
    'paymentStatus.refunded': 'Refunded',
    
    // Payment Methods
    'paymentMethod.bankTransfer': 'Bank Transfer',
    'paymentMethod.creditCard': 'Credit Card',
    'paymentMethod.cash': 'Cash',
    'paymentMethod.check': 'Check',
    
    // Leads
    'leads.title': 'Leads Inbox',
    'leads.subtitle': 'Manage and track your sales leads',
    'leads.addLead': 'Add Lead',
    'leads.totalLeads': 'Total Leads',
    'leads.qualified': 'Qualified',
    'leads.pendingFollowUp': 'Pending Follow-up',
    'leads.totalValue': 'Total Value',
    'leads.filterByStatus': 'Filter by Status',
    'leads.searchPlaceholder': 'Search leads by name, company, or email...',
    'leads.sortByDate': 'Sort by Date',
    'leads.sortByValue': 'Sort by Value',
    'leads.sortByScore': 'Sort by Score',
    'leads.lastContact': 'Last contact',
    'leads.followUp': 'Follow up',
    'leads.viewDetails': 'View Details',
    'leads.edit': 'Edit',
    'leads.call': 'Call',
    'leads.email': 'Email',
    'leads.noLeads': 'No leads found',
    'leads.noLeadsDesc': 'Try adjusting your search or filter criteria',
    'leads.yesterday': 'Yesterday',
    'leads.daysAgo': 'days ago',
    'leads.allLeads': 'All Leads',
    'leads.leadScore': 'Lead Score',
    'leads.company': 'Company',
    'leads.phone': 'Phone',
    
    // Lead Statuses
    'leadStatus.new': 'New',
    'leadStatus.contacted': 'Contacted',
    'leadStatus.qualified': 'Qualified',
    'leadStatus.proposal': 'Proposal',
    'leadStatus.won': 'Won',
    'leadStatus.lost': 'Lost',
    
    // Profile
    'profile.companyInfoTitle': 'Company Information',
    'profile.companyInfoSubtitle': 'Manage your company profile and business details',
    'profile.editProfile': 'Edit Profile',
    'profile.cancel': 'Cancel',
    'profile.saveChanges': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.changeLogo': 'Change Logo',
    'profile.basicInformation': 'Basic Information',
    'profile.contactInformation': 'Contact Information',
    'profile.companyDescription': 'Company Description',
    'profile.accountStatus': 'Account Status',
    'profile.companyName': 'Company Name',
    'profile.industry': 'Industry',
    'profile.founded': 'Founded',
    'profile.employees': 'Number of Employees',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.website': 'Website',
    'profile.address': 'Address',
    'profile.aboutCompany': 'About Your Company',
    'profile.notProvided': 'Not provided',
    'profile.accountVerified': 'Account Verified',
    'profile.documentsApproved': 'All documents approved',
    'profile.premiumMember': 'Premium Member',
    'profile.fullAccess': 'Full platform access',
    'profile.kycCompleted': 'KYC Completed',
    'profile.identityVerified': 'Identity verified',
    
    // Profile Validation
    'validation.companyNameRequired': 'Company name is required',
    'validation.emailRequired': 'Email is required',
    'validation.invalidEmail': 'Invalid email format',
    'validation.phoneRequired': 'Phone number is required',
    'validation.addressRequired': 'Address is required',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.products': 'المنتجات',
    'nav.orders': 'الطلبات',
    'nav.communication': 'التواصل',
    'nav.finance': 'المالية',
    'nav.leads': 'العملاء المحتملين',
    'nav.profile': 'الملف الشخصي',
    'nav.analytics': 'التحليلات',
    
    // Products
    'products.title': 'قائمة المنتجات',
    'products.subtitle': 'إدارة كتالوج المنتجات والمخزون',
    'products.addProduct': 'إضافة منتج',
    'products.totalProducts': 'إجمالي المنتجات',
    'products.activeProducts': 'منتجات نشطة',
    'products.lowStock': 'مخزون منخفض',
    'products.outOfStock': 'نفد المخزون',
    'products.search': 'البحث في المنتجات، الأكواد، أو الفئات...',
    'products.filters': 'الفلاتر',
    'products.category': 'الفئة',
    'products.status': 'الحالة',
    'products.stockLevel': 'مستوى المخزون',
    'products.priceRange': 'نطاق الأسعار',
    'products.allCategories': 'جميع الفئات',
    'products.allStatuses': 'جميع الحالات',
    'products.allLevels': 'جميع المستويات',
    'products.allPrices': 'جميع الأسعار',
    'products.clearFilters': 'مسح جميع الفلاتر',
    'products.selected': 'تم تحديد',
    'products.updateStatus': 'تحديث الحالة',
    'products.updateStock': 'تحديث المخزون',
    'products.delete': 'حذف',
    'products.product': 'المنتج',
    'products.price': 'السعر',
    'products.stock': 'المخزون',
    'products.sales': 'المبيعات',
    'products.actions': 'إجراءات',
    'products.units': 'وحدة',
    'products.sold': 'مبيعة',
    'products.loadMore': 'عرض المزيد',
    'products.remaining': 'منتج متبقي',
    'products.noProducts': 'لا توجد منتجات',
    'products.noProductsDesc': 'لم يتم العثور على منتجات تطابق معايير البحث والفلترة.',
    
    // Product Status
    'status.active': 'نشط',
    'status.inactive': 'غير نشط',
    'status.draft': 'مسودة',
    'status.outOfStock': 'نفد المخزون',
    
    // Stock Levels
    'stock.inStock': 'متوفر',
    'stock.lowStock': 'مخزون منخفض',
    'stock.outOfStock': 'نفد المخزون',
    
    // Price Ranges
    'price.under1000': 'أقل من 1,000 ريال',
    'price.1000to5000': '1,000 - 5,000 ريال',
    'price.5000to20000': '5,000 - 20,000 ريال',
    'price.over20000': 'أكثر من 20,000 ريال',
    
    // Add/Edit Product
    'addProduct.title': 'إضافة منتج جديد',
    'editProduct.title': 'تعديل المنتج',
    'addProduct.step': 'الخطوة',
    'addProduct.of': 'من',
    'addProduct.saving': 'جاري الحفظ...',
    'addProduct.saved': 'تم الحفظ',
    'addProduct.saveError': 'خطأ في الحفظ',
    'addProduct.basicInfo': 'المعلومات الأساسية',
    'addProduct.detailsMedia': 'التفاصيل والوسائط',
    'addProduct.pricingInventory': 'الأسعار والمخزون',
    'addProduct.reviewPublish': 'المراجعة والنشر',
    'addProduct.nameEn': 'اسم المنتج (بالإنجليزية)',
    'addProduct.nameAr': 'اسم المنتج (بالعربية)',
    'addProduct.sku': 'رمز المنتج (SKU)',
    'addProduct.category': 'الفئة',
    'addProduct.selectCategory': 'اختر الفئة',
    'addProduct.tags': 'العلامات (Tags)',
    'addProduct.addTag': 'إضافة',
    'addProduct.descriptionEn': 'الوصف (بالإنجليزية)',
    'addProduct.descriptionAr': 'الوصف (بالعربية)',
    'addProduct.images': 'صور المنتج (حد أقصى 10 صور)',
    'addProduct.dragImages': 'اسحب الصور هنا أو اضغط للاختيار',
    'addProduct.imageFormat': 'PNG، JPG، GIF حتى 10MB لكل صورة',
    'addProduct.specifications': 'المواصفات الفنية',
    'addProduct.addSpec': 'إضافة مواصفة',
    'addProduct.sellingPrice': 'سعر البيع (ريال سعودي)',
    'addProduct.costPrice': 'سعر التكلفة (ريال سعودي)',
    'addProduct.stockQuantity': 'الكمية المتوفرة',
    'addProduct.lowStockThreshold': 'حد التنبيه للمخزون المنخفض',
    'addProduct.dimensions': 'الأبعاد والوزن',
    'addProduct.length': 'الطول (سم)',
    'addProduct.width': 'العرض (سم)',
    'addProduct.height': 'الارتفاع (سم)',
    'addProduct.weight': 'الوزن (كجم)',
    'addProduct.productStatus': 'حالة المنتج',
    'addProduct.review': 'مراجعة المنتج',
    'addProduct.productInfo': 'معلومات المنتج',
    'addProduct.statusSettings': 'الحالة والإعدادات',
    'addProduct.name': 'الاسم',
    'addProduct.productCode': 'رمز المنتج',
    'addProduct.stockCount': 'المخزون',
    'addProduct.imageCount': 'الصور',
    'addProduct.specCount': 'المواصفات',
    'addProduct.tagCount': 'العلامات',
    'addProduct.description': 'الوصف',
    'addProduct.previous': 'السابق',
    'addProduct.next': 'التالي',
    'addProduct.saveChanges': 'حفظ التغييرات',
    'addProduct.publishProduct': 'نشر المنتج',
    'addProduct.unsavedChanges': 'لديك تغييرات غير محفوظة',
    'addProduct.saveNow': 'حفظ الآن',
    'addProduct.profitMargin': 'هامش الربح',
    'addProduct.lowStockAlert': 'سيتم تنبيهك عند وصول المخزون لهذا العدد',
    'addProduct.autoSku': 'سيتم توليد رمز تلقائياً بناءً على اسم المنتج',
    
    // Validation Messages
    'validation.required': 'هذا الحقل مطلوب',
    'validation.nameRequired': 'اسم المنتج مطلوب',
    'validation.nameArRequired': 'الاسم العربي مطلوب',
    'validation.skuRequired': 'رمز المنتج مطلوب',
    'validation.categoryRequired': 'الفئة مطلوبة',
    'validation.descriptionRequired': 'الوصف مطلوب',
    'validation.descriptionArRequired': 'الوصف العربي مطلوب',
    'validation.priceRequired': 'السعر يجب أن يكون أكبر من صفر',
    'validation.stockNegative': 'المخزون لا يمكن أن يكون سالباً',
    'validation.fixErrors': 'يجب إصلاح الأخطاء التالية:',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.settings': 'إعدادات',
    
    // Orders
    'orders.title': 'إدارة الطلبات',
    'orders.subtitle': 'إدارة ومتابعة طلبات العملاء',
    'orders.totalOrders': 'إجمالي الطلبات',
    'orders.pendingOrders': 'طلبات معلقة',
    'orders.completedOrders': 'طلبات مكتملة',
    'orders.cancelledOrders': 'طلبات ملغاة',
    'orders.search': 'البحث في الطلبات، العملاء، أو المنتجات...',
    'orders.orderNumber': 'رقم الطلب',
    'orders.customer': 'العميل',
    'orders.date': 'تاريخ الطلب',
    'orders.total': 'المبلغ الإجمالي',
    'orders.status': 'الحالة',
    'orders.actions': 'إجراءات',
    'orders.viewDetails': 'عرض التفاصيل',
    'orders.contactCustomer': 'التواصل مع العميل',
    'orders.updateStatus': 'تحديث الحالة',
    'orders.generateInvoice': 'إنشاء فاتورة',
    'orders.noOrders': 'لا توجد طلبات',
    'orders.noOrdersDesc': 'لم يتم العثور على طلبات تطابق معايير البحث والفلترة.',
    'orders.filterBy': 'تصفية حسب',
    'orders.allStatuses': 'جميع الحالات',
    'orders.dateRange': 'نطاق التاريخ',
    'orders.customerType': 'نوع العميل',
    'orders.orderValue': 'قيمة الطلب',
    'orders.bulkActions': 'إجراءات جماعية',
    'orders.selectedOrders': 'طلب محدد',
    'orders.markAsProcessing': 'وضع علامة قيد المعالجة',
    'orders.markAsShipped': 'وضع علامة تم الشحن',
    'orders.markAsDelivered': 'وضع علامة تم التسليم',
    'orders.exportSelected': 'تصدير المحدد',
    'orders.orderDetails': 'تفاصيل الطلب',
    'orders.orderTimeline': 'جدول زمني للطلب',
    'orders.paymentInfo': 'معلومات الدفع',
    'orders.shippingInfo': 'معلومات الشحن',
    'orders.customerInfo': 'معلومات العميل',
    'orders.orderItems': 'عناصر الطلب',
    'orders.orderSummary': 'ملخص الطلب',
    'orders.subtotal': 'المجموع الفرعي',
    'orders.tax': 'ضريبة القيمة المضافة (15%)',
    'orders.shipping': 'الشحن',
    'orders.discount': 'الخصم',
    'orders.grandTotal': 'المجموع الإجمالي',
    
    // Order Statuses
    'orderStatus.pending': 'في الانتظار',
    'orderStatus.confirmed': 'مؤكد',
    'orderStatus.processing': 'قيد المعالجة',
    'orderStatus.shipped': 'تم الشحن',
    'orderStatus.delivered': 'تم التسليم',
    'orderStatus.cancelled': 'ملغى',
    'orderStatus.refunded': 'مسترد',
    
    // Communication
    'communication.title': 'مركز التواصل',
    'communication.subtitle': 'إدارة تواصل العملاء والاستفسارات',
    'communication.activeChats': 'المحادثات النشطة',
    'communication.unreadMessages': 'رسائل غير مقروءة',
    'communication.searchCustomers': 'البحث عن العملاء...',
    'communication.allPriorities': 'جميع الأولويات',
    'communication.highPriority': 'أولوية عالية',
    'communication.mediumPriority': 'أولوية متوسطة',
    'communication.lowPriority': 'أولوية منخفضة',
    'communication.online': 'متصل الآن',
    'communication.lastSeen': 'آخر ظهور',
    'communication.typeMessage': 'اكتب رسالتك...',
    'communication.selectChat': 'اختر محادثة للبدء',
    'communication.selectChatDesc': 'اختر عميل من القائمة لعرض محادثتك معه',
    'communication.newConversation': 'محادثة جديدة',
    'communication.templates': 'القوالب',
    'communication.quickReplies': 'ردود سريعة',
    'communication.attachments': 'المرفقات',
    'communication.emoji': 'الرموز التعبيرية',
    'communication.send': 'إرسال',
    'communication.minutes': 'د',
    'communication.hours': 'س',
    'communication.days': 'ي',
    'communication.priority': 'الأولوية',
    'communication.tags': 'العلامات',
    'communication.customerInfo': 'معلومات العميل',
    'communication.conversationHistory': 'تاريخ المحادثة',
    'communication.orderHistory': 'تاريخ الطلبات',
    'communication.notes': 'الملاحظات',
    'communication.addNote': 'إضافة ملاحظة',
    'communication.markAsRead': 'وضع علامة كمقروء',
    'communication.markAsImportant': 'وضع علامة كمهم',
    'communication.archive': 'الأرشفة',
    'communication.block': 'حظر العميل',
    'communication.call': 'اتصال',
    'communication.videoCall': 'مكالمة فيديو',
    'communication.email': 'البريد الإلكتروني',
    
    // Finance
    'finance.title': 'لوحة المالية',
    'finance.subtitle': 'تتبع الإيرادات والمدفوعات والتقارير المالية',
    'finance.totalRevenue': 'إجمالي الإيرادات',
    'finance.pendingPayments': 'مدفوعات معلقة',
    'finance.overduePayments': 'مدفوعات متأخرة',
    'finance.averagePaymentTime': 'متوسط زمن الدفع',
    'finance.transactions': 'معاملة',
    'finance.days': 'يوم',
    'finance.fromLastMonth': 'من الشهر الماضي',
    'finance.exportReport': 'تصدير التقرير',
    'finance.revenueOverTime': 'اتجاه الإيرادات',
    'finance.paymentMethods': 'طرق الدفع',
    'finance.recentTransactions': 'المعاملات الأخيرة',
    'finance.invoiceNumber': 'رقم الفاتورة',
    'finance.customer': 'العميل',
    'finance.amount': 'المبلغ',
    'finance.status': 'الحالة',
    'finance.paymentMethod': 'طريقة الدفع',
    'finance.dueDate': 'تاريخ الاستحقاق',
    'finance.actions': 'إجراءات',
    'finance.allStatuses': 'جميع الحالات',
    'finance.revenue': 'الإيرادات',
    'finance.payments': 'المدفوعات',
    'finance.period': 'الفترة',
    'finance.week': 'أسبوع',
    'finance.month': 'شهر',
    'finance.quarter': 'ربع سنة',
    'finance.year': 'سنة',
    
    // Payment Statuses
    'paymentStatus.paid': 'مدفوع',
    'paymentStatus.pending': 'معلق',
    'paymentStatus.overdue': 'متأخر',
    'paymentStatus.failed': 'فشل',
    'paymentStatus.refunded': 'مسترد',
    
    // Payment Methods
    'paymentMethod.bankTransfer': 'حوالة بنكية',
    'paymentMethod.creditCard': 'بطاقة ائتمان',
    'paymentMethod.cash': 'نقداً',
    'paymentMethod.check': 'شيك',
    
    // Leads
    'leads.title': 'صندوق العملاء المحتملين',
    'leads.subtitle': 'إدارة ومتابعة عملائك المحتملين',
    'leads.addLead': 'إضافة عميل محتمل',
    'leads.totalLeads': 'إجمالي العملاء المحتملين',
    'leads.qualified': 'مؤهل',
    'leads.pendingFollowUp': 'في انتظار المتابعة',
    'leads.totalValue': 'القيمة الإجمالية',
    'leads.filterByStatus': 'تصفية حسب الحالة',
    'leads.searchPlaceholder': 'البحث عن العملاء بالاسم أو الشركة أو البريد...',
    'leads.sortByDate': 'ترتيب حسب التاريخ',
    'leads.sortByValue': 'ترتيب حسب القيمة',
    'leads.sortByScore': 'ترتيب حسب النقاط',
    'leads.lastContact': 'آخر تواصل',
    'leads.followUp': 'متابعة',
    'leads.viewDetails': 'عرض التفاصيل',
    'leads.edit': 'تعديل',
    'leads.call': 'اتصال',
    'leads.email': 'بريد إلكتروني',
    'leads.noLeads': 'لا توجد عملاء محتملين',
    'leads.noLeadsDesc': 'جرب تعديل معايير البحث أو التصفية',
    'leads.yesterday': 'أمس',
    'leads.daysAgo': 'أيام مضت',
    'leads.allLeads': 'جميع العملاء المحتملين',
    'leads.leadScore': 'نقاط العميل',
    'leads.company': 'الشركة',
    'leads.phone': 'الهاتف',
    
    // Lead Statuses
    'leadStatus.new': 'جديد',
    'leadStatus.contacted': 'تم التواصل',
    'leadStatus.qualified': 'مؤهل',
    'leadStatus.proposal': 'عرض',
    'leadStatus.won': 'فائز',
    'leadStatus.lost': 'خاسر',
    
    // Profile
    'profile.companyInfoTitle': 'معلومات الشركة',
    'profile.companyInfoSubtitle': 'إدارة ملف شركتك وتفاصيل العمل',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.cancel': 'إلغاء',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.saving': 'جاري الحفظ...',
    'profile.changeLogo': 'تغيير الشعار',
    'profile.basicInformation': 'المعلومات الأساسية',
    'profile.contactInformation': 'معلومات الاتصال',
    'profile.companyDescription': 'وصف الشركة',
    'profile.accountStatus': 'حالة الحساب',
    'profile.companyName': 'اسم الشركة',
    'profile.industry': 'الصناعة',
    'profile.founded': 'تاريخ التأسيس',
    'profile.employees': 'عدد الموظفين',
    'profile.email': 'عنوان البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.website': 'الموقع الإلكتروني',
    'profile.address': 'العنوان',
    'profile.aboutCompany': 'عن شركتك',
    'profile.notProvided': 'غير مقدم',
    'profile.accountVerified': 'تم التحقق من الحساب',
    'profile.documentsApproved': 'تم اعتماد جميع المستندات',
    'profile.premiumMember': 'عضو مميز',
    'profile.fullAccess': 'وصول كامل للمنصة',
    'profile.kycCompleted': 'تم إكمال اعرف عميلك',
    'profile.identityVerified': 'تم التحقق من الهوية',
    
    // Profile Validation
    'validation.companyNameRequired': 'اسم الشركة مطلوب',
    'validation.emailRequired': 'البريد الإلكتروني مطلوب',
    'validation.invalidEmail': 'تنسيق بريد إلكتروني غير صحيح',
    'validation.phoneRequired': 'رقم الهاتف مطلوب',
    'validation.addressRequired': 'العنوان مطلوب',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    return translations[language][key as keyof typeof translations.en] || fallback || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    isRTL: language === 'ar',
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};